# Generated by Django 5.0 on 2023-12-28 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Product_Name')),
                ('details', models.CharField(max_length=50, verbose_name='Product_Details')),
                ('Price', models.FloatField()),
                ('catagory', models.IntegerField(choices=[(1, 'Shirts'), (2, 'T-shirts'), (3, 'Jeans'), (4, 'Joggers'), (5, 'Undergarments')])),
                ('availability', models.BooleanField(default=True, verbose_name='Product Active/Inactive')),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cstoreapp.product')),
            ],
        ),
    ]
